## Common configuration section
[General]

# Information label
labelInfo = Peridiniella_chain_STRAT2

# Base path to save the model and its results
modelBasePath = ./data/PeridiniellaChain_STRAT2/

# Save results to NPZ files?
npzSave = False

# Image dimensions
imHeight = 64
imWidth = 256
imChannel = 3

# Indices of the test images to plot (nok samples in the first half)
imIndxList = 0, 15, 25, 35


## Training configuration section
[Training]

# Selected model from ModelSaved module
layerSel = ConvM1, ConvM2, ConvM3, ConvM4, ConvM5, ConvM6
modelSel = BAE1, BAE2, VAE1, VAE2, VQVAE1

# Path to training dataset
datasetPath = ../../Datasets/Plankton_Strategies/Peridiniella_catenata_chain/Peridiniella_catenata_chain2/

# Batch size
batchSize = 20

# Number of epochs
numEpoch = 500
